JDF-338 Upgrade Cordova lib version from 2.0.0. to 2.7.0

diff --git a/kitchensink-cordova/ios/cordova/emulate b/kitchensink-cordova/ios/cordova/emulate
--- a/kitchensink-cordova/ios/cordova/emulate
+++ b/kitchensink-cordova/ios/cordova/emulate
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 #
 # Licensed to the Apache Software Foundation (ASF) under one
 # or more contributor license agreements.  See the NOTICE file
@@ -7,9 +7,9 @@
 # to you under the Apache License, Version 2.0 (the
 # "License"); you may not use this file except in compliance
 # with the License.  You may obtain a copy of the License at
-# 
+#
 # http://www.apache.org/licenses/LICENSE-2.0
-# 
+#
 # Unless required by applicable law or agreed to in writing,
 # software distributed under the License is distributed on an
 # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
@@ -20,38 +20,35 @@
 
 set -e
 
-CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd )
-PROJECT_PATH=$CORDOVA_PATH/..
+XCODE_VER=$(xcodebuild -version | head -n 1 | sed -e 's/Xcode //')
+XCODE_MIN_VERSION="4.5"
 
-function getAppPath() {
-	for file in $PROJECT_PATH/*.xcodeproj; do
-	  PROJECT_NAME=$(basename "$file" .xcodeproj)
-	done;
-	APP=build/$PROJECT_NAME.app
-	APP_PATH=$PROJECT_PATH/$APP
-}
+if [[ "$XCODE_VER" < "$XCODE_MIN_VERSION" ]]; then
+	echo "Cordova can only run in Xcode version $XCODE_MIN_VERSION or greater."
+	exit 1
+fi
 
-APP_PATH=$1
+CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd -P)
+PROJECT_PATH="$(dirname "$CORDOVA_PATH")"
+XCODEPROJ=$( ls "$PROJECT_PATH" | grep .xcodeproj  )
+PROJECT_NAME=$(basename "$XCODEPROJ" .xcodeproj)
 
-if [ $# -lt 1 ]; then
-	getAppPath
+APP_PATH=${1:-$PROJECT_PATH/build/$PROJECT_NAME.app}
+DEVICE_FAMILY=${2:-${DEVICE_FAMILY:-iphone}}
+
+if [ ! -d "$APP_PATH" ]; then
+	echo "Project '$APP_PATH' is not built. Building."
+    $CORDOVA_PATH/build || exit $?
 fi
 
 if [ ! -d "$APP_PATH" ]; then
-	read -p "Project '$APP_PATH' is not built. Build? [y/n]: " REPLY 
-	if [ "$REPLY" == "y" ]; then 
-		$CORDOVA_PATH/debug
-		exit 0
-	else 
-		echo "$APP_PATH not found to emulate."
-		exit 1
-	fi	
+	echo "$APP_PATH not found to emulate."
+	exit 1
 fi
 
 # launch using ios-sim
-
 if which ios-sim >/dev/null; then
-    ios-sim launch $APP_PATH --stderr console.log --stdout console.log &
+    ios-sim launch "$APP_PATH" --family "$DEVICE_FAMILY" --stderr "$CORDOVA_PATH/console.log" --stdout "$CORDOVA_PATH/console.log" &
 else
     echo -e '\033[31mError: ios-sim was not found. Please download, build and install version 1.4 or greater from https://github.com/phonegap/ios-sim into your path. Or "brew install ios-sim" using homebrew: http://mxcl.github.com/homebrew/\033[m'; exit 1;
 fi
